* Just For Fun Benchmark for combinations

I like combiantions. and I found my module competitive with others.
At the same time I'd like to improve my code as well.
And I always had weakness on testing code. I'm going to study about it.

** Language Available

*** HACKING Golang
    I am trying to code in many language but
    `golang` is super fast for any imperative implementation.
    * [X] /no-crossed-fingers/ method (my own method)
    * [ ] recursive method
      - after haskell resursive version
    * [ ]bench mark by using *go test* [1/3]
      * [ ] put the module into separate file and load from `_test.go`
      * [ ] no-crossed-finger(jeongoon: me)
      * [X] https://github.com/notnil/combos


*** TODO Haskell [0/2]
    - [ ] follwers & leaders version (my first try)
    - [ ] tail after tail version (my second try)
     * How to benchmark??
 
*** TODO Perl
    Coming soon. This is my original vesion of /no-crossed-fingers/ method

    

* Recursive Combinations cannot beat the Imperative Combinations?

Still I have no idea, however imperative my implentation tends to
win the race over recursive one.
