name:                haskell-combinations
version:             0.1.0.0
license:             OSL-3.0
github:              "jeongoon/combinations-bench"
author:              "Myoungjin Jeon <jeongoon@gmail.com>"
maintainer:          "jeongoon@gmail.com"
copyright:           "Myoungjin Jeon <jeongoon@gmail.com>"

extra-source-files:
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Some Combinations implementation with Benchmark
category:            Algorithm

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jeongoon/haskell-combinations#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  haskell-combinations-benchmark-exe:
    main:               Bench.lhs
    source-dirs:        benchmark
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-combinations
    - criterion

tests:
  haskell-combinations-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-combinations

benchmarks:
  haskell-combinations-benchmark:
    main:               Bench.lhs
    source-dirs:        benchmark
    ghc-options:
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-combinations
    - criterion

  take-vs-pattern-matching-benchmark:
    main:               BenchPatternMatchingOrTake.lhs
    source-dirs:        benchmark2
    ghc-options:
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-combinations
    - criterion
